export const gallery = [
    { id: 1, photo: "/1.jpg", heading: "Best Couple Pic" },
    { id: 2, photo: "/2.jpg", heading: "Random Click" },
    { id: 3, photo: "/3.png", heading: "Last year's Valentine" },
    { id: 4, photo: "/4.jpg", heading: "Parampara Winning Moment" },
    { id: 5, photo: "/5.jpg", heading: "First Date Outside" },
    { id: 6, photo: "/6.jpg", heading: "Having Pizza on Date" },
    { id: 7, photo: "/7.jpg", heading: "Corona Time" },
    { id: 8, photo: "/8.jpg", heading: "Cuteness at peak" },
    { id: 9, photo: "/9.jpg", heading: "Parampara Promotion" },
    { id: 10, photo: "/10.jpg", heading: "Nauka ka Nazara" },
    { id: 11, photo: "/11.jpg", heading: "Ek aur couple pic" },
    { id: 12, photo: "/12.jpg", heading: "Kya Date thi" },
    { id: 13, photo: "/13.jpg", heading: "This was awesome" },
    { id: 14, photo: "/14.jpg", heading: "First Movie" },
    { id: 15, photo: "/15.jpg", heading: "Band Room" },
    { id: 16, photo: "/16.jpg", heading: "First Pic Together" },
    { id: 17, photo: "/17.jpg", heading: "Collage of pics" },
    { id: 18, photo: "/18.jpg", heading: "Zoo mein Enjoy" },
    { id: 19, photo: "/19.jpg", heading: "My Farewell" },
    { id: 20, photo: "/20.jpg", heading: "One more cute pic" },
];